import type { ParsedAgent, GeneratedFile } from "../parser";
import { formatParams } from "../parser";

const MODEL_MAP: Record<string, string> = {
  haiku:  "claude-haiku-4-5",
  sonnet: "claude-sonnet-4-6",
  opus:   "claude-opus-4-7",
};

function sdkModel(model?: string): string {
  return model ? (MODEL_MAP[model] ?? model) : "claude-opus-4-7";
}

// ── Param helpers ─────────────────────────────────────────────────────────────

interface ParamDef { name: string; tsType: string; jsonType: string }

const TS_TYPE_MAP: Record<string, string> = {
  str: "string", string: "string",
  int: "number", integer: "number",
  float: "number", number: "number", double: "number",
  bool: "boolean", boolean: "boolean",
};

const JSON_TYPE_MAP: Record<string, string> = {
  str: "string", string: "string",
  int: "integer", integer: "integer",
  float: "number", number: "number", double: "number",
  bool: "boolean", boolean: "boolean",
};

function parseParams(raw: string): ParamDef[] {
  if (!raw || raw === "void") return [];
  // Already-formatted: "file (string), depth (number)"
  if (raw.includes("(")) {
    return raw.split(",").map((p) => {
      const m = p.trim().match(/^(\w+)\s*\((\w+)\)$/);
      if (!m) return { name: p.trim(), tsType: "string", jsonType: "string" };
      const type = m[2]!;
      return { name: m[1]!, tsType: TS_TYPE_MAP[type] ?? type, jsonType: JSON_TYPE_MAP[type] ?? "string" };
    });
  }
  // Raw: "str file, int depth"
  return raw.split(",").map((p) => {
    const parts   = p.trim().split(/\s+/);
    if (parts.length < 2) return { name: parts[0]!, tsType: "string", jsonType: "string" };
    const rawType = parts.slice(0, -1).join(" ").replace(/\*+$/, "").trim();
    const name    = parts[parts.length - 1]!.replace(/^\*+/, "");
    return { name, tsType: TS_TYPE_MAP[rawType] ?? rawType, jsonType: JSON_TYPE_MAP[rawType] ?? "string" };
  });
}

function toPascalCase(s: string): string {
  return s
    .replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase());
}

// ── Code generator ────────────────────────────────────────────────────────────

export function generateSdkAgentTs(agent: ParsedAgent): string {
  const fm         = agent.frontmatter;
  const model      = sdkModel(fm.model);
  const isOpus     = !fm.model || fm.model === "opus";
  const isHaiku    = fm.model === "haiku";
  const toolSkills = agent.skills.filter((s) => !s.inline);
  const inlSkills  = agent.skills.filter((s) => s.inline);
  const maxTurns   = fm.maxTurns ? parseInt(fm.maxTurns, 10) : 20;
  const hasEffort  = !!fm.effort && !isHaiku;

  // System prompt — optionally extend with inline skills
  let systemPrompt = agent.systemPrompt;
  if (inlSkills.length > 0) {
    const inlLines: string[] = ["", "## Skills", ""];
    for (const s of inlSkills) {
      inlLines.push(`### ${s.name}`);
      const p = formatParams(s.params);
      if (p) inlLines.push(`Parameters: ${p}`);
      inlLines.push("", s.body, "");
    }
    systemPrompt = (systemPrompt + inlLines.join("\n")).trimEnd();
  }

  const sections: string[] = [];

  sections.push(
`// Generated by cagents — do not edit
import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
`
  );

  if (toolSkills.length === 0) {
    // No tool skills — single call, no loop needed
    const thinking = isOpus    ? `\n    thinking: { type: "adaptive" },`                         : "";
    const effort   = hasEffort ? `\n    output_config: { effort: ${JSON.stringify(fm.effort)} },` : "";

    sections.push(
`export async function run(prompt: string): Promise<string> {
  const response = await client.messages.create({
    model: ${JSON.stringify(model)},
    max_tokens: 16000,${thinking}${effort}
    system: [{ type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } }],
    messages: [{ role: "user", content: prompt }],
  });
  return response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("");
}`
    );
  } else {
    const skillParams = new Map(toolSkills.map((s) => [s.name, parseParams(s.params)]));

    // TOOLS array
    const toolEntries = toolSkills.map((skill) => {
      const params   = skillParams.get(skill.name)!;
      const descLine = skill.body.split("\n").find((l) => l.trim()) ?? skill.name;
      const propsBody = params.length > 0
        ? [
            `      properties: {`,
            ...params.map((p) => `        ${p.name}: { type: ${JSON.stringify(p.jsonType)} as const },`),
            `      },`,
            `      required: [${params.map((p) => JSON.stringify(p.name)).join(", ")}],`,
          ].join("\n")
        : `      properties: {},`;
      return [
        `  {`,
        `    name: ${JSON.stringify(skill.name)},`,
        `    description: ${JSON.stringify(descLine.trim())},`,
        `    input_schema: {`,
        `      type: "object" as const,`,
        propsBody,
        `    },`,
        `  }`,
      ].join("\n");
    });

    sections.push(
`const TOOLS: Anthropic.Tool[] = [
${toolEntries.join(",\n")}
];
`
    );

    // TypeScript input types
    const typeBlocks = toolSkills.map((skill) => {
      const params   = skillParams.get(skill.name)!;
      const typeName = toPascalCase(skill.name) + "Input";
      return params.length > 0
        ? `export type ${typeName} = {\n${params.map((p) => `  ${p.name}: ${p.tsType};`).join("\n")}\n};`
        : `export type ${typeName} = Record<string, never>;`;
    });
    sections.push(typeBlocks.join("\n") + "\n");

    // ToolHandlers export type
    const handlerLines = toolSkills
      .map((skill) => `  ${skill.name}: (input: ${toPascalCase(skill.name)}Input) => Promise<string>;`)
      .join("\n");
    sections.push(
`export type ToolHandlers = {
${handlerLines}
};
`
    );

    // run() with tool loop
    const thinking = isOpus    ? `\n      thinking: { type: "adaptive" },`                         : "";
    const effort   = hasEffort ? `\n      output_config: { effort: ${JSON.stringify(fm.effort)} },` : "";
    const cases    = toolSkills.map((skill) => {
      const typeName = toPascalCase(skill.name) + "Input";
      return `          case ${JSON.stringify(skill.name)}: result = await handlers.${skill.name}(block.input as ${typeName}); break;`;
    }).join("\n");

    sections.push(
`export async function run(prompt: string, handlers: ToolHandlers): Promise<string> {
  const messages: Anthropic.MessageParam[] = [{ role: "user", content: prompt }];
  for (let turn = 0; turn < ${maxTurns}; turn++) {
    const response = await client.messages.create({
      model: ${JSON.stringify(model)},
      max_tokens: 16000,${thinking}${effort}
      system: [{ type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } }],
      tools: TOOLS,
      messages,
    });
    messages.push({ role: "assistant", content: response.content });
    if (response.stop_reason !== "tool_use") {
      return response.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("");
    }
    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    for (const block of response.content) {
      if (block.type !== "tool_use") continue;
      let result: string;
      try {
        switch (block.name) {
${cases}
          default: result = \`Unknown tool: \${block.name}\`;
        }
      } catch (err) {
        result = \`Error: \${err instanceof Error ? err.message : String(err)}\`;
      }
      toolResults.push({ type: "tool_result", tool_use_id: block.id, content: result });
    }
    messages.push({ role: "user", content: toolResults });
  }
  return "Max turns reached";
}`
    );
  }

  return sections.join("\n").trimEnd() + "\n";
}

export function generateSdkFiles(agent: ParsedAgent): GeneratedFile[] {
  return [
    { path: `${agent.name}.ts`, content: generateSdkAgentTs(agent) },
  ];
}
