import { test, expect, describe } from "bun:test";
import { parseCAgent } from "../parser";
import { generateSdkAgentTs, generateSdkFiles } from "./claude_sdk";

function parse(src: string) {
  return parseCAgent(src.trim() + "\n");
}

const MINIMAL = `
#def name my-agent

fn main() {
\tYou are a helpful assistant.
}
`;

const FULL = `
#def name reviewer
#def description Reviews code carefully
#def model opus
#def effort high
#def maxTurns 50

fn review(str file, int depth) {
\tReview the given file.
\tdepth controls thoroughness.
}

fn main() {
\tYou are a code reviewer.
\tBe direct.
}
`;

const WITH_SONNET = `
#def name summarizer
#def model sonnet

fn main() {
\tYou summarize text.
}
`;

const WITH_HAIKU = `
#def name classifier
#def model haiku
#def effort high

fn main() {
\tYou classify text.
}
`;

const WITH_SKILL_ONLY = `
#def name my-agent

fn greet(str name) {
\tSay hello to the user by name.
}

fn main() {
\tYou are a greeter.
}
`;

const WITH_INLINE_SKILL = `
#def name my-agent

#pragma inline
fn ping() {
\tRespond with pong.
}

fn main() {
\tYou are a test agent.
}
`;

const WITH_MULTI_SKILLS = `
#def name researcher
#def model opus

fn search(str query) {
\tSearch for query.
}

fn summarize(str text, int words) {
\tSummarize text in words words.
}

fn main() {
\tYou are a research agent.
}
`;

const WITH_ALL_TYPES = `
#def name typed-agent

fn process(str text, int count, float score, bool verbose) {
\tProcess the input.
}

fn main() {
\tYou process data.
}
`;

// ── Output path ───────────────────────────────────────────────────────────────

describe("sdk — output path", () => {
  test("generates a single TypeScript file named <agent>.ts", () => {
    const files = generateSdkFiles(parse(MINIMAL));
    expect(files).toHaveLength(1);
    expect(files[0]!.path).toBe("my-agent.ts");
  });

  test("uses the agent name from frontmatter", () => {
    const files = generateSdkFiles(parse(FULL));
    expect(files[0]!.path).toBe("reviewer.ts");
  });
});

// ── Imports and client ────────────────────────────────────────────────────────

describe("sdk — imports", () => {
  test("imports Anthropic from @anthropic-ai/sdk", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('import Anthropic from "@anthropic-ai/sdk"');
  });

  test("creates a default Anthropic client", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain("const client = new Anthropic()");
  });

  test("file starts with generated comment", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts.startsWith("// Generated by cagents")).toBe(true);
  });
});

// ── System prompt ─────────────────────────────────────────────────────────────

describe("sdk — system prompt", () => {
  test("single-line prompt emitted as string literal", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('const SYSTEM_PROMPT = "You are a helpful assistant."');
  });

  test("multi-line prompt encoded as single JSON string with \\n escapes", () => {
    const ts = generateSdkAgentTs(parse(FULL));
    expect(ts).toContain("You are a code reviewer.\\nBe direct.");
  });

  test("system prompt used with cache_control ephemeral", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('cache_control: { type: "ephemeral" }');
    expect(ts).toContain("text: SYSTEM_PROMPT");
  });
});

// ── Model mapping ─────────────────────────────────────────────────────────────

describe("sdk — model mapping", () => {
  test("no model defaults to claude-opus-4-7", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('model: "claude-opus-4-7"');
  });

  test("opus maps to claude-opus-4-7", () => {
    const ts = generateSdkAgentTs(parse(FULL));
    expect(ts).toContain('model: "claude-opus-4-7"');
  });

  test("sonnet maps to claude-sonnet-4-6", () => {
    const ts = generateSdkAgentTs(parse(WITH_SONNET));
    expect(ts).toContain('model: "claude-sonnet-4-6"');
  });

  test("haiku maps to claude-haiku-4-5", () => {
    const ts = generateSdkAgentTs(parse(WITH_HAIKU));
    expect(ts).toContain('model: "claude-haiku-4-5"');
  });
});

// ── Thinking ──────────────────────────────────────────────────────────────────

describe("sdk — adaptive thinking", () => {
  test("opus model includes adaptive thinking", () => {
    const ts = generateSdkAgentTs(parse(FULL));
    expect(ts).toContain('thinking: { type: "adaptive" }');
  });

  test("no model (defaults opus) includes adaptive thinking", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('thinking: { type: "adaptive" }');
  });

  test("sonnet model does not include thinking block", () => {
    const ts = generateSdkAgentTs(parse(WITH_SONNET));
    expect(ts).not.toContain("thinking:");
  });

  test("haiku model does not include thinking block", () => {
    const ts = generateSdkAgentTs(parse(WITH_HAIKU));
    expect(ts).not.toContain("thinking:");
  });
});

// ── Effort ────────────────────────────────────────────────────────────────────

describe("sdk — effort", () => {
  test("effort is emitted inside output_config", () => {
    const ts = generateSdkAgentTs(parse(FULL));
    expect(ts).toContain('output_config: { effort: "high" }');
  });

  test("haiku ignores effort even when specified", () => {
    const ts = generateSdkAgentTs(parse(WITH_HAIKU));
    expect(ts).not.toContain("output_config:");
  });

  test("no effort means no output_config", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).not.toContain("output_config:");
  });
});

// ── No-tool agent (simple run) ────────────────────────────────────────────────

describe("sdk — no-tool agent", () => {
  test("run takes only prompt parameter", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain("export async function run(prompt: string): Promise<string>");
  });

  test("no-tool agent does not define TOOLS", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).not.toContain("const TOOLS");
  });

  test("no-tool agent does not define ToolHandlers", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).not.toContain("ToolHandlers");
  });

  test("no-tool agent returns text directly", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts).toContain('filter((b): b is Anthropic.TextBlock => b.type === "text")');
    expect(ts).toContain(".map((b) => b.text)");
  });
});

// ── Tool definitions ──────────────────────────────────────────────────────────

describe("sdk — TOOLS array", () => {
  test("non-inline skill produces a TOOLS entry", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("const TOOLS: Anthropic.Tool[]");
    expect(ts).toContain('name: "greet"');
  });

  test("tool input_schema has type object as const", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('type: "object" as const');
  });

  test("skill params become properties with correct JSON types", () => {
    const ts = generateSdkAgentTs(parse(WITH_ALL_TYPES));
    expect(ts).toContain('text: { type: "string" as const }');
    expect(ts).toContain('count: { type: "integer" as const }');
    expect(ts).toContain('score: { type: "number" as const }');
    expect(ts).toContain('verbose: { type: "boolean" as const }');
  });

  test("required array lists all params", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('required: ["name"]');
  });

  test("no-param skill has empty properties and no required array", () => {
    const ts = generateSdkAgentTs(parse(WITH_INLINE_SKILL));
    // ping is inline so TOOLS should not appear
    expect(ts).not.toContain("const TOOLS");
  });

  test("multiple skills produce multiple TOOLS entries", () => {
    const ts = generateSdkAgentTs(parse(WITH_MULTI_SKILLS));
    expect(ts).toContain('name: "search"');
    expect(ts).toContain('name: "summarize"');
  });
});

// ── TypeScript types ──────────────────────────────────────────────────────────

describe("sdk — TypeScript input types", () => {
  test("skill gets a PascalCase Input type", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("export type GreetInput = {");
    expect(ts).toContain("  name: string;");
  });

  test("str→string, int→number type mapping in TS type", () => {
    const ts = generateSdkAgentTs(parse(WITH_MULTI_SKILLS));
    expect(ts).toContain("export type SummarizeInput = {");
    expect(ts).toContain("  text: string;");
    expect(ts).toContain("  words: number;");
  });

  test("no-param skill gets Record<string, never> type", () => {
    // Create an agent with a non-inline no-param skill
    const agent = parse(`
#def name test-agent

fn ping() {
\tPong.
}

fn main() {
\tTest agent.
}
`.trim() + "\n");
    const ts = generateSdkAgentTs(agent);
    expect(ts).toContain("export type PingInput = Record<string, never>");
  });

  test("ToolHandlers type is exported", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("export type ToolHandlers = {");
    expect(ts).toContain("  greet: (input: GreetInput) => Promise<string>;");
  });
});

// ── Tool loop ─────────────────────────────────────────────────────────────────

describe("sdk — tool use loop", () => {
  test("run takes prompt and handlers when skills exist", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("export async function run(prompt: string, handlers: ToolHandlers): Promise<string>");
  });

  test("loop iterates maxTurns times (default 20)", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("turn < 20");
  });

  test("maxTurns from frontmatter overrides default", () => {
    const ts = generateSdkAgentTs(parse(FULL));
    expect(ts).toContain("turn < 50");
  });

  test("breaks out of loop when stop_reason is not tool_use", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('response.stop_reason !== "tool_use"');
  });

  test("switch statement handles each skill by name", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('case "greet"');
    expect(ts).toContain("handlers.greet(block.input as GreetInput)");
  });

  test("switch has default case for unknown tools", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("default: result = `Unknown tool: ${block.name}`");
  });

  test("tool results are pushed back as user message", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('"tool_result"');
    expect(ts).toContain("tool_use_id: block.id");
  });

  test("returns Max turns reached if loop exhausts", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain('"Max turns reached"');
  });

  test("errors in handlers are caught and returned as strings", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts).toContain("err instanceof Error ? err.message : String(err)");
  });
});

// ── Inline skills ─────────────────────────────────────────────────────────────

describe("sdk — inline skills", () => {
  test("inline skill is embedded in system prompt, not as tool", () => {
    const ts = generateSdkAgentTs(parse(WITH_INLINE_SKILL));
    expect(ts).not.toContain("const TOOLS");
    expect(ts).toContain("## Skills");
    expect(ts).toContain("### ping");
    expect(ts).toContain("Respond with pong.");
  });

  test("inline skill does not generate a ToolHandlers type", () => {
    const ts = generateSdkAgentTs(parse(WITH_INLINE_SKILL));
    expect(ts).not.toContain("ToolHandlers");
  });
});

// ── Output format ─────────────────────────────────────────────────────────────

describe("sdk — output format", () => {
  test("output ends with newline", () => {
    const ts = generateSdkAgentTs(parse(MINIMAL));
    expect(ts.endsWith("\n")).toBe(true);
  });

  test("output ends with newline (with skills)", () => {
    const ts = generateSdkAgentTs(parse(WITH_SKILL_ONLY));
    expect(ts.endsWith("\n")).toBe(true);
  });
});
